export const languages = [
    { name: "English", code: "en-US" },
    { name: "中文 (简体)", code: "zh-CN" },
    { name: "中文 (繁體)", code: "zh-TW" },
    { name: "हिन्दी (Hindi)", code: "hi-IN" },
    { name: "Español", code: "es-ES" },
    { name: "Français", code: "fr-FR" },
    { name: "العربية (Arabic)", code: "ar-SA" },
    { name: "বাংলা (Bengali)", code: "bn-BD" },
    { name: "Português", code: "pt-BR" },
    { name: "Русский (Russian)", code: "ru-RU" },
    { name: "اردو (Urdu)", code: "ur-PK" },
    { name: "Bahasa Indonesia", code: "id-ID" },
    { name: "Deutsch", code: "de-DE" },
    { name: "日本語 (Japanese)", code: "ja-JP" },
    { name: "Nigerian Pidgin", code: "pcm-NG" },
    { name: "मराठी (Marathi)", code: "mr-IN" },
    { name: "తెలుగు (Telugu)", code: "te-IN" },
    { name: "Türkçe", code: "tr-TR" },
    { name: "தமிழ் (Tamil)", code: "ta-IN" },
    { name: "廣東話 (Cantonese)", code: "yue-HK" },
    { name: "Tiếng Việt", code: "vi-VN" },
    { name: "Tagalog", code: "tl-PH" },
    { name: "吴语 (Wu Chinese)", code: "wuu-CN" },
    { name: "한국어 (Korean)", code: "ko-KR" },
    { name: "فارسی (Persian)", code: "fa-IR" },
    { name: "Hausa", code: "ha-NG" },
    { name: "Kiswahili", code: "sw-KE" },
    { name: "Basa Jawa (Javanese)", code: "jv-ID" },
    { name: "Italiano", code: "it-IT" },
    { name: "ਪੰਜਾਬੀ (Punjabi)", code: "pa-PK" },
    { name: "ಕನ್ನಡ (Kannada)", code: "kn-IN" },
    { name: "ગુજરાતી (Gujarati)", code: "gu-IN" },
    { name: "ไทย (Thai)", code: "th-TH" },
    { name: "አማርኛ (Amharic)", code: "am-ET" },
    { name: "भोजपुरी (Bhojpuri)", code: "bho-IN" },
    { name: "閩南語 (Hokkien)", code: "nan-TW" },
    { name: "晋语 (Jin Chinese)", code: "cjy-CN" },
    { name: "Yorùbá", code: "yo-NG" },
    { name: "客家话 (Hakka)", code: "hak-CN" },
    { name: "မြန်မာစာ (Burmese)", code: "my-MM" },
    { name: "ଓଡ଼ିଆ (Odia)", code: "or-IN" },
    { name: "Afaan Oromoo", code: "om-ET" },
    { name: "پښتو (Pashto)", code: "ps-AF" },
    { name: "Kurdî (Kurdish)", code: "ku-TR" },
    { name: "Asụsụ Igbo", code: "ig-NG" },
    { name: "മലയാളം (Malayalam)", code: "ml-IN" },
    { name: "الدارجة (Algerian Arabic)", code: "ar-DZ" },
    { name: "Azərbaycan dili", code: "az-AZ" },
    { name: "Polski", code: "pl-PL" },
    { name: "Oʻzbekcha", code: "uz-UZ" },
    { name: "سنڌي (Sindhi)", code: "sd-PK" }
];
